/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.pantallas;

import juego.Juego;
import juego.negocio.JuegoCompartido;
import cliente.ClienteSocket;
import cliente.ClienteUtils;
import cliente.Despachador;
import cliente.escuchadores.EscuchadorConexion;
import cliente.escuchadores.EscuchadorMensajes;
import cliente.eventos.Cliente;
import cliente.eventos.EventoCliente;
import cliente.eventos.EventoMensaje;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo
 */
public class PantallaLogin extends javax.swing.JFrame implements EscuchadorConexion, EscuchadorMensajes{
    
    private ClienteSocket clienteSocket;

    /**
     * Creates new form PantallaLogin
     */
    public PantallaLogin() {
        initComponents();
        
        Despachador.listaEscuchadores.add(EscuchadorConexion.class, this);
        Despachador.listaEscuchadores.add(EscuchadorMensajes.class, this);
        JuegoCompartido.clienteSocket = new ClienteSocket("localhost", 81);
        clienteSocket = JuegoCompartido.clienteSocket;
        clienteSocket.Iniciar();
        
//        txt_passwordlogin.addActionListener((e) -> {btn_login.doClick();});
        txt_userlogin.addActionListener(e -> btn_login.doClick());
        txt_passwordlogin.addActionListener(e -> btn_login.doClick());
        
        txt_userreg.addActionListener(e -> btn_registrar.doClick());
        txt_passwordreg2.addActionListener( e -> btn_registrar.doClick());
        txt_passwordreg1.addActionListener(e -> btn_registrar.doClick());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_estadoconexion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_userlogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_passwordlogin = new javax.swing.JPasswordField();
        chkbox_verpasswordLogin = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_userreg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_passwordreg1 = new javax.swing.JPasswordField();
        txt_passwordreg2 = new javax.swing.JPasswordField();
        btn_registrar = new javax.swing.JButton();
        chkbox_verpasswordReg = new javax.swing.JCheckBox();
        lbl_idcliente = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbl_estadoconexion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_estadoconexion.setForeground(new java.awt.Color(255, 0, 0));
        lbl_estadoconexion.setText("Desconectado");

        btn_login.setText("Login");
        btn_login.setEnabled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        chkbox_verpasswordLogin.setText("ver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_userlogin)
                    .addComponent(txt_passwordlogin))
                .addGap(6, 6, 6)
                .addComponent(chkbox_verpasswordLogin)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_userlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_passwordlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbox_verpasswordLogin))
                .addGap(18, 18, 18)
                .addComponent(btn_login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Contraseña:");

        txt_passwordreg1.setNextFocusableComponent(txt_passwordreg2);

        btn_registrar.setText("Registrar");
        btn_registrar.setEnabled(false);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        chkbox_verpasswordReg.setText("ver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_passwordreg2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_passwordreg1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txt_userreg))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkbox_verpasswordReg))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_registrar)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_userreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_passwordreg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkbox_verpasswordReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_passwordreg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_registrar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lbl_idcliente.setText("ID asignado =");

        btn_logout.setText("Logout");
        btn_logout.setEnabled(false);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jLabel6.setText("Socket:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_estadoconexion))
                    .addComponent(lbl_idcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_estadoconexion)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_idcliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_logout)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.println("Ventana Closing !!");
        clienteSocket.Detener();
    }//GEN-LAST:event_formWindowClosing

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String user = txt_userlogin.getText();
        String password = new String(txt_passwordlogin.getPassword());
        if (!user.isEmpty() && !password.isEmpty()) {
            clienteSocket.Loguear(user, password);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campos llenados incorrectamente!");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        String user = txt_userreg.getText();
        String password1 = new String(txt_passwordreg1.getPassword());
        String password2 = new String(txt_passwordreg2.getPassword());
        if (!user.isEmpty() && !password1.isEmpty() && !password2.isEmpty()) {
            if (password1.equals(password2)) {
                clienteSocket.Registrar(user, password1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Los passwords no coinciden!!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campos llenados incorrectamente!");
        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PantallaLogin().setVisible(true);

//                PantallaLogin pantallaLogin = new PantallaLogin();
//                pantallaLogin.setVisible(true);
//                pantallaLogin.btn_logout.setVisible(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JCheckBox chkbox_verpasswordLogin;
    private javax.swing.JCheckBox chkbox_verpasswordReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_estadoconexion;
    private javax.swing.JLabel lbl_idcliente;
    private javax.swing.JPasswordField txt_passwordlogin;
    private javax.swing.JPasswordField txt_passwordreg1;
    private javax.swing.JPasswordField txt_passwordreg2;
    private javax.swing.JTextField txt_userlogin;
    private javax.swing.JTextField txt_userreg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnConectado(EventoCliente eventoCliente) {
        lbl_estadoconexion.setForeground(Color.green);
        lbl_estadoconexion.setText("Conectado");
        btn_login.setEnabled(true);
        btn_registrar.setEnabled(true);
    }

    @Override
    public void OnDesconectado(EventoCliente eventoCliente) {
        lbl_estadoconexion.setForeground(Color.red);
        lbl_estadoconexion.setText("Desconectado");
        btn_login.setEnabled(false);
        btn_registrar.setEnabled(false);
    }

    @Override
    public void OnMensajeRecibido(EventoMensaje eventoMensaje) {
        System.out.println("ON MENSAJE RECIBIDO PL !!!");
    }

    @Override
    public void OnIdentificado(EventoMensaje eventoMensaje) {
        lbl_idcliente.setText(String.valueOf( "ID asignado = " + clienteSocket.getEventoClienteS().getCliente().getId()));
        System.out.println("ON IDENTIFICADO PL !!!");
    }

    @Override
    public void OnLoginOK(EventoMensaje eventoMensaje) {
        String resString = ClienteUtils.LeerOK(eventoMensaje.getMensaje().getMensajeServidor());
        int res = Integer.parseInt(resString);
        switch (res) {
            case 0:
                //no se pudo loguear, no coinciden ambos datos
                txt_userlogin.setText("");
                txt_passwordlogin.setText("");
                JOptionPane.showMessageDialog(rootPane, "Usuario no existe !!");
                break;
            case 1:
                //logueado exitosamente
                Cliente cli = clienteSocket.getEventoClienteS().getCliente();
                cli.setLogin(true);
                cli.setUser(txt_userlogin.getText());
                cli.setPassword(new String(txt_passwordlogin.getPassword()));
                cli.setId(Long.parseLong(ClienteUtils.LeerOKnewID(eventoMensaje.getMensaje().getMensajeServidor())));
                
                lbl_idcliente.setText(String.valueOf( "ID asignado = " + cli.getId()));
                btn_login.setEnabled(false);
                btn_registrar.setEnabled(false);
                btn_logout.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "Logueado Exitosamente !!");
                
                this.setVisible(false);
                Juego.pantallaJuego.setVisible(true);
                
                clienteSocket.ComenzarPartida();
                break;
            case 2:
                //contrasenha incorrecta
                JOptionPane.showMessageDialog(rootPane, "Contrasenha Incorrecta !!");
            default:
                System.out.println("Ocurrio un error al loguearse!!");
        }
    }

    @Override
    public void OnRegistroOK(EventoMensaje eventoMensaje) {
        int res = Integer.parseInt(eventoMensaje.getMensaje().getMensajeServidor());
        switch (res) {
            case 0:
                //no se pudo registrar
                //clienteSocket.getEventoClienteS().getCliente().Limpiar();
                JOptionPane.showMessageDialog(rootPane, "No se pudo registrar. Nombre de usuario ya existe !!");
                break;
            case 1:
                //registrado exitosamente
                txt_userreg.setText("");
                txt_passwordreg1.setText("");
                txt_passwordreg2.setText("");
                
                JOptionPane.showMessageDialog(rootPane, "Registrado Exitosamente !!");
                
                break;
            default:
                System.out.println("Ocurrio un error al Registrarse!!");
        }
    }

    @Override
    public void OnComerzarPartidaOK(EventoMensaje eventoMensaje) {
        //
    }

    @Override
    public void OnUnJugadorDesconectado(EventoMensaje eventoMensaje) {
        //
    }

    @Override
    public void OnUnJugadorConectado(EventoMensaje eventoMensaje) {
        //
    }

    @Override
    public void OnGastarTurnoOK(EventoMensaje eventoMensaje) {
        //
    }

    @Override
    public void OnHayPartidaEnCurso(EventoMensaje eventoMensaje) {
        //
    }
}
